version: '3.8'
services:
  php:
    image: shin1x1/php-dev:8.1.2-fpm-buster
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
    working_dir: /var/www/html
  composer:
    image: composer:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  phpstan:
    image: ghcr.io/phpstan/phpstan
    volumes:
      - .:/app
    working_dir: /app
